### ISSUE TITLE
Align all blue CSS colors to the same as home page header image

### ISSUE THREAD

**Issue by notthetup** [org-arl/unet-blog#10]
_From @sayanee on September 3, 2018 12:55_

- [x] hyperlink `a` tag
    ![image](https://user-images.githubusercontent.com/413879/44987836-32c02b00-afbb-11e8-9b70-350a7f40b00c.png)
- [x] social button
    ![image](https://user-images.githubusercontent.com/413879/44987936-85014c00-afbb-11e8-9757-f5258e35cede.png)
- [x] amend the blue color everywhere else in the CSS code

_Copied from original issue: notthetup/unet-blog#4_

**Comment by AnneThKu** [comment]
modified the blue color for the buttons and hyperlinks.
Before:
<img width="1392" alt="issue10_before" src="https://user-images.githubusercontent.com/42397354/45538036-80009000-b838-11e8-8570-54e9c74406eb.png">

After:
<img width="1379" alt="issue10_after" src="https://user-images.githubusercontent.com/42397354/45538040-842cad80-b838-11e8-9f30-947b42a91a84.png">

**Comment by notthetup** [comment]
Fixed in 0added324f4db24167c1b0099455a29f602c0219
