### ISSUE TITLE
Add a background color for code tags

### ISSUE THREAD

**Issue by notthetup** [org-arl/unet-blog#11]
_From @sayanee on September 3, 2018 12:57_

![image](https://user-images.githubusercontent.com/413879/44988008-c8f45100-afbb-11e8-99e9-e6afa8ea3c27.png)

Maybe the same yellow as [Unet stack main website](https://unetstack.net/docs.html):

![image](https://user-images.githubusercontent.com/413879/44988052-f50fd200-afbb-11e8-9c6f-122f2fdfe537.png)

_Copied from original issue: notthetup/unet-blog#5_

**Comment by AnneThKu** [comment]
A grey background added for the code tags. Please check if ok.

<img width="960" alt="code_tags_1" src="https://user-images.githubusercontent.com/42397354/45532890-432c9d00-b828-11e8-8d6c-6123352084e8.png">

<img width="936" alt="code_tags_2" src="https://user-images.githubusercontent.com/42397354/45532903-57709a00-b828-11e8-960f-94a787de3406.png">

**Comment by manuignatius** [comment]
Looks good to me too!

**Comment by notthetup** [comment]
Fixed in c07e84804
