### ISSUE TITLE
Add profile page links to authors name in the blog

### ISSUE THREAD

**Issue by manuignatius** [org-arl/unet-blog#15]

**Comment by AnneThKu** [comment]
Modified author name as link.

<img width="910" alt="profilelinks" src="https://user-images.githubusercontent.com/42397354/45606439-b0823d00-ba77-11e8-83a4-226ce3394598.png">

An authors.yml file has been added, where the profile page links have to be updated by the author.
<img width="190" alt="ymlfilescreenshot" src="https://user-images.githubusercontent.com/42397354/45606454-cd1e7500-ba77-11e8-8a47-c9c1e6ece88e.png">

**Comment by notthetup** [comment]
Fixed in 5581
