### ISSUE TITLE
Add author name to the main blog page

### ISSUE THREAD

**Issue by manuignatius** [org-arl/unet-blog#18]
Currently the author name only appear inside the blog post (against potentially distracting background), not in the main page. Suggest adding it there (as shown below), using the same format.

<img width="787" alt="screen shot 2018-09-19 at 9 49 08 am" src="https://user-images.githubusercontent.com/4144181/45726335-54432880-bbf1-11e8-9656-a4b3b2378f17.png">

**Comment by AnneThKu** [comment]
Added author name in main page.

<img width="917" alt="issue18-author name" src="https://user-images.githubusercontent.com/42397354/45728148-57daad80-bbf9-11e8-8a64-f42aaaf34edd.png">

**Comment by notthetup** [comment]
Fixed in 80166cb10
