### ISSUE TITLE
Transponder use cases 

### ISSUE THREAD

**Issue by prasadtiru** [org-arl/unet-blog#4]
The intent of this post is to explain the following:
  - To be able to configure the acoustic modem as a transponder
  - To be able to query a transponder
  - Positioning with transponder using Time of Arrival (ToA)
  - demonstrate how to get the waveforms (baseband reception, rssi, impulse response etc for path planning)

**Comment by manuignatius** [comment]
Transponder details in this paper: [Baseband Signal Processing with UnetStack](https://arl.nus.edu.sg/twiki6/pub/ARL/BibEntries/sdmodem.pdf)

**Comment by manuignatius** [comment]
https://blog.unetstack.net/AUV-to-transponder-Range-Estimation-Application-using-UnetStack
